plugins:
  - rubocop-performance

inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - vendor

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Performance/RedundantBlockCall:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
